name: SNANA image build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dotenv Action
        uses: falti/dotenv-action@v0.2.8
        with:
          path: astrodocker/snana/env.public
      - name: test image build
        run: cd astrodocker/snana/ && bash build.sh