name: SNANA image build

on:
  push:
    branches: [main]
    paths:
      - astrodocker/snana/*
  pull_request:
    branches: [main]
    paths:
      - astrodocker/snana/*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test image build
        run: cd astrodocker/snana/ && bash build.sh