name: Docker image builds

on:
  push:
    branches: [main]
    paths:
      - "*/Dockerfile"
      - ".github/workflows/publish_docker_image.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build pyraf
        id: pyraf_build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./astrodocker/pyraf
          file: ./astrodocker/pyraf/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          push: false
