name: Publish Docker image

# This workflow manages the testing, building, and publishing of docker images
# On a pull request to main:
#   If docker related files are changed, the image is test built and not published
# On a push to main (or a new tag is created on master):
#   The docker image is built and tagged with latest and and / or new tag version

on:
  push:
    branches: [main]
    paths:
      - "*/Dockerfile"
      - ".github/workflows/publish_docker_image.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build pyraf
        id: pyraf_build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./astrodocker/pyraf
          file: ./astrodocker/pyraf/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          push: false
